version: '3'
services:

  db:
    image: postgres:latest

    # Это небезопасно, но сделано намерено для вашего удобства
    environment:
      - POSTGRES_DB=flask_db
      - POSTGRES_USER=flask_user
      - POSTGRES_PASSWORD=flask_password

    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8000:5000"
    env_file:
      - .env
    volumes:
      - .:/app

volumes:
  dbdata: